### ISSUE TITLE
Your New Machine homepage section

### ISSUE THREAD

**Issue by indieinc** [GitGuild/tigoctm#19]
## Description

The "Your New Machine" section of the site should utilize the [Lamassu Slide](https://lamassu.is/products) as outlined in [the wiki](https://github.com/GitGuild/tigoctm/wiki/Website-Copy#section-9). The design and colors should match the overall theme of the TigoCTM site.

There are a few ways of accomplishing this. The current layout of the section could be updated with proper pictures of each CTM and links to a product page for each More Info button. Alternatively, just the button slides at the top of the [Lamassu product section](https://lamassu.is/products) can be placed in that section, with each linking to the product page for its respective CTM.

## Tasks

- [x] Correct pictures of each CTM
- [x] Add modal functionality to "More Info" buttons
- [ ] Write/adapt copy for all 3 CTMs
- [ ] Add copy for all 3 CTMs to their respective "More Info" buttons
- [x] Ensure design & colors mesh with TigoCTM's theme

**Comment by isysd** [comment]
@cindy-zimmerman @glenkow would you work with @indieinc to adapt the required copy for this section? If any specific design things are needed, please attempt or document as a separate task.

**Comment by indieinc** [comment]
We'll need copy and stats for each of the three CTM products in the section. Not sure if the copy from the [Lamassu products page](https://lamassu.is/products) would suffice or if we should give just a brief summary.

Will also need to decide on how to integrate the copy. Each "More Info" button could link to a page mirroring its respective info page [on Lamassu's site](https://lamassu.is/product/douro/).

**Comment by indieinc** [comment]
@cindy-zimmerman Are the graphics from Lamassu okay to use? If so, do you want them re-colored from teal to TigoCTM colors?

**Comment by isysd** [comment]
The graphics are OK to use. Please do minimal re-branding for now... we'll do a careful job of it in the future.

**Comment by indieinc** [comment]
@cindy-zimmerman Is there a Press/Partner pack that the needed graphics could be sourced from? I can recolor them.

**Comment by indieinc** [comment]
Update on integration of copy into the site.

Title of each machine will go on top of each picture. Need input on one point. Should I place the copy in a short list underneath each picture, or should all of that come up in each respective modal instead?

The latter option is easier to integrate into the homepage - no concerns about resizing elements or  interfering with other sections.

**Comment by glenkow** [comment]
I'd just go with the latter option unless the information makes the page 
look unbalanced or the columns too narrow.



On 7/14/16 2:08 PM, Tyler DuPre wrote:
>
> Update on integration of copy into the site.
>
> Title of each machine will go on top of each picture. Need input on 
> one point. Should I place the copy in a short list underneath each 
> picture, or should all of that come up in each respective modal instead?
>
> The latter option is easier to integrate into the homepage - no 
> concerns about resizing elements or interfering with other sections.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/GitGuild/tigoctm/issues/19#issuecomment-232762425>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ATaw7xIDOidj93xZFMKSATfdtUQadodYks5qVokrgaJpZM4JLiCo>.
>

-- 
Glen Kowalski
glen@glenkowalski.com
http://www.glenkowalski.com

**Comment by isysd** [comment]
# Git Guild Bounty Program

| Total | Dev               | Sales | Reporter | Tester(s) | Maintainer | Documenter |
|--------|------------------|---------|-------------|------------|-----------------|----------------|
|N/A    | assignee(s)   | @isysd  | @indieinc | @cindy-zimmerman, @d3brouille | @cindy-zimmerman | @d3brouille |
| $165 | $99 | $8.25 | $8.25 | $33 | $8.25 | $8.25 |

**Comment by cindy-zimmerman** [comment]
@indieinc @glenkow @isysd For the moment Tigo CTM is an official reseller of Lamassu machines.  So for now reusing descriptions/pictures of Lamassu machines is good.  This will most likely change in the future so I don't want to spend too much time perfecting it.  Just something that will will look decent will work.

**Comment by indieinc** [comment]
@cindy-zimmerman Which bits of the copy for each product should be included?
