### ISSUE TITLE
Products page

### ISSUE THREAD

**Issue by indieinc** [GitGuild/tigoctm#20]
## Description

The products page of TigoCTM should implement the slides from [Lamassu's products page](https://lamassu.is/products). Colors and navigation bar should be consistent with TigoCTM's theme and site. Branding on the page should be TigoCTM's.

##  Tasks
- [ ] Implement Lamassu slides
- [ ] Ensure colors/design match TigoCTM
- [ ] Change branding/navigation bar to be consistent with rest of site
