### ISSUE TITLE
Homepage dynamic element movement

### ISSUE THREAD

**Issue by indieinc** [GitGuild/tigoctm#24]
## Description

Elements on the page should move in response to user interaction, like scrolling. For example, elements move in dynamically from the edges upon scrolling [on the Lamassu homepage.](https://lamassu.is/)

## Tasks

- [ ] Separate elements to allow for movement
- [ ] Add dynamic movement to the navigation bar
- [ ] Add dynamic movement to the infographic
- [ ] Add dynamic movement to other elements of the homepage
