### ISSUE TITLE
"TIGO" should really be "TigoCTM" for branding purposes in copy

### ISSUE THREAD

**Issue by cindy-zimmerman** [GitGuild/tigoctm#25]
There are a few places in the copy where TIGO is a place holder for TigoCTM.  These should be replaced with the proper TigoCTM.  

@glenkow please correct me if I'm wrong, just trying to make the branding consistent

**Comment by indieinc** [comment]
@isysd This might be able to be added to #21 as one of the tasks.

**Comment by glenkow** [comment]
You are 100% correct.

**Comment by indieinc** [comment]
@cindy-zimmerman @glenkow On [the mirror of the site](https://indieinc.github.io/), under the "The Business Opportunity" section, there's a line that reads: 

> 
**TIGO Cryptocurrency Teller Machines (CTM’s)** eliminate these issues by making Bitcoin and Cryptocurrency transactions as simple as using your bank’s ATM.
> 

How should this be changed?

**Comment by indieinc** [comment]
## Description
Occurrences of the word "TIGO" should be replaced with "TigoCTM". Occurrences of the phrase "Tigo CTM" should be concatenated into a single word - "TigoCTM".

Occurrences appear throughout the homepage, including on the infographic. 

## Tasks

- [ ] Change all occurrences of "TIGO" or "Tigo CTM" to "TigoCTM"
  - [ ] "The Business Opportunity" section
  - [ ] Infographic section
  - [ ] "Recover Your Investment" section

**Comment by isysd** [comment]
```
 find ./ -type f | xargs sed -i 's/TIGO CTM/TigoCTM/'
 find ./ -type f | xargs sed -i 's/TIGO/TigoCTM/'
```
